# Generated by Django 5.2.3 on 2025-06-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=7)),
                ('dre_classification', models.CharField(choices=[('receita_bruta', 'Receita Bruta'), ('deducao_venda', 'Dedução de Venda'), ('custos_variaveis', 'Custos Variáveis'), ('despesa_operacional', 'Despesa Operacional'), ('despesa_administrativa', 'Despesa Administrativa'), ('despesa_comercial', 'Despesa Comercial'), ('receita_financeira', 'Receita Financeira'), ('despesa_financeira', 'Despesa Financeira'), ('imposto_lucro', 'Imposto sobre o Lucro'), ('nao_se_aplica', 'Não se Aplica')], max_length=30)),
                ('dfc_classification', models.CharField(choices=[('operacional', 'Operacional'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento'), ('nao_se_aplica', 'Não se Aplica')], max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'unique_together': {('company', 'name')},
            },
        ),
    ]
