# Generated by Django 5.2.3 on 2025-08-06 13:37

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('type', models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança'), ('Caixa', 'Caixa'), ('Investimento', 'Investimento'), ('Outro', 'Outro')], max_length=20, verbose_name='Tipo de Conta')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=7)),
                ('dre_classification', models.CharField(choices=[('receita_bruta', 'Receita Bruta'), ('deducao_venda', 'Dedução de Venda'), ('custos_variaveis', 'Custos Variáveis'), ('despesa_operacional', 'Despesa Operacional'), ('despesa_administrativa', 'Despesa Administrativa'), ('despesa_comercial', 'Despesa Comercial'), ('receita_financeira', 'Receita Financeira'), ('despesa_financeira', 'Despesa Financeira'), ('imposto_lucro', 'Imposto sobre o Lucro'), ('nao_se_aplica', 'Não se Aplica')], max_length=30)),
                ('dfc_classification', models.CharField(choices=[('operacional', 'Operacional'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento'), ('nao_se_aplica', 'Não se Aplica')], max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cartão')),
                ('brand', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Elo', 'Elo'), ('American Express', 'American Express'), ('Hipercard', 'Hipercard'), ('Diners Club', 'Diners Club'), ('Outra', 'Outra')], max_length=20, verbose_name='Bandeira')),
                ('last_digits', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Limite de Crédito')),
                ('closing_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Fechamento')),
                ('due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('associated_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='finance.bankaccount', verbose_name='Conta Associada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'unique_together': {('company', 'last_digits')},
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor a Receber')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('received', 'Recebido'), ('overdue', 'Vencido')], default='pending', max_length=10, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('pix', 'PIX'), ('boleto', 'Boleto')], max_length=15, verbose_name='Forma de Pagamento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='accounts.company', verbose_name='Empresa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='cadastros.customer', verbose_name='Cliente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='saida', max_length=7)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.company')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.creditcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor a Pagar')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='pendente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payables', to='accounts.company')),
                ('paid_from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payables', to='finance.bankaccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payables', to='finance.transaction', verbose_name='Transação de Origem (Cartão)')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['due_date'],
            },
        ),
    ]
