# Generated by Django 5.2.3 on 2025-06-27 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('type', models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança'), ('Caixa', 'Caixa'), ('Investimento', 'Investimento'), ('Outro', 'Outro')], max_length=20, verbose_name='Tipo de Conta')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'unique_together': {('company', 'name')},
            },
        ),
    ]
