# Generated by Django 5.2.3 on 2025-06-27 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0002_bankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('transaction_date', models.DateField(verbose_name='Data da Transação')),
                ('type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=7, verbose_name='Tipo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.bankaccount', verbose_name='Conta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category', verbose_name='Categoria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.company')),
                ('user', models.ForeignKey(help_text='Usuário que registrou a transação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
