# Generated by Django 5.2.3 on 2025-06-27 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cartão')),
                ('brand', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Elo', 'Elo'), ('American Express', 'American Express'), ('Hipercard', 'Hipercard'), ('Diners Club', 'Diners Club'), ('Outra', 'Outra')], max_length=20, verbose_name='Bandeira')),
                ('last_digits', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Limite de Crédito')),
                ('closing_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Fechamento')),
                ('due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('associated_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='finance.bankaccount', verbose_name='Conta Associada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'unique_together': {('company', 'last_digits')},
            },
        ),
    ]
