# Generated by Django 5.2.3 on 2025-07-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_supplier_supplieraddress_supplierbankaccount'),
        ('finance', '0004_receivable'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='cadastros.supplier', verbose_name='Fornecedor'),
        ),
    ]
