# Generated by Django 5.2.3 on 2025-07-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payable_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payable',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Receivable',
        ),
    ]
