# Generated by Django 5.2.3 on 2025-07-12 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cadastros', '0002_supplier_supplieraddress_supplierbankaccount'),
        ('finance', '0006_remove_payable_supplier_delete_receivable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor a Receber')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('received', 'Recebido'), ('overdue', 'Vencido')], default='pending', max_length=10, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('pix', 'PIX'), ('boleto', 'Boleto')], max_length=15, verbose_name='Forma de Pagamento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='accounts.company', verbose_name='Empresa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='cadastros.customer', verbose_name='Cliente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['due_date'],
            },
        ),
    ]
