# Generated by Django 5.2.3 on 2025-07-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions_list',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Lista de Permissões'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('finance', 'Financeiro'), ('manager', 'Gestor'), ('analyst', 'Analista'), ('employee', 'Colaborador')], default='admin', max_length=20, verbose_name='Cargo'),
        ),
    ]
