# Generated by Django 5.2.3 on 2025-07-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_permissions_list_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='BRL', max_length=5, verbose_name='Moeda Padrão'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='pt-BR', max_length=10, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_bills_reminder',
            field=models.BooleanField(default=True, verbose_name='Lembrete de contas a pagar'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_large_transactions',
            field=models.BooleanField(default=True, verbose_name='Notificar grandes transações'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_weekly_goals',
            field=models.BooleanField(default=True, verbose_name='Notificar metas semanais'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='light', max_length=10, verbose_name='Tema'),
        ),
    ]
